### ISSUE TITLE
Utility Viewer - Discrepancies - Attaching Photos/Documents

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#123]
Please add the ability to attach photos and other files to discrepancy points.

**Comment by jday3** [comment]
I've added the photo functionality, but adding other documents will take a decent effort. Currently there is only a Photos table in the Discrepancies database. If you think it is worth it to include uploads other than photos, let me know

**Comment by jday3** [comment]
on dev, btw

**Comment by JMurk** [comment]
Confirmed complete, please push to prod.  I think the next step on this is possibly allowing users to view the associated photos in the Utility Viewer.

**Comment by jday3** [comment]
Pushed to production

**Comment by jday3** [comment]
For viewing associated photos I would think we would have a window that displays the discrepancy information and the list of photos and clicking on a photo would open the picture. Maybe we put a button on the toolbar next to the add discrepancy button that allows the user to identify discrepancies or instead offer an option in the regular results display.

**Comment by JMurk** [comment]
Could we potentially add this to the attached documents window?

![image](https://cloud.githubusercontent.com/assets/5805454/9792516/7fade4b0-57ae-11e5-9078-1d6c1527c6f0.png)

**Comment by taojun545** [comment]
Updated on dev.
1. Allow user to click button and open attached documents window for all kinds of Discrepancies.
2. Add new grid "Discrepancy Photos" into window, and load the associated photos. User can click thumbnail to see full image.

**Comment by JMurk** [comment]
That looks good... A couple things:
- Is it possible to make each section collapsible? If so, please do so and set them to be collapsed when no data exists within the section.
- The CCTV Videos panel can be shorter, about half the size that it is now.
- Can you hide the CCTV Videos panel until the tool is selected for specific features?  If so, those features would be Active Sewer Mains, Force Mains, Abandoned Sewer Mains.

**Comment by taojun545** [comment]
I think show/hide will be a good idea. I updated followings on dev:
- "Discrepancy Photos" section will be shown only when selected a discrepancy.
- "CCTV Videos" section will be shown only when selected is "Active Sewer Mains" or "Lateral Address Points".
- "OnBase Documents" section will be shown only when selected has "DOCPOPURL" property.

For your questions,
1. Since we already have show/hide function, do we still need collapse/expand function?
2. If "CCTV Videos" panel is shown, "Discrepancy Photos" panel will be hidden. So the height of the panel will not be an issue. Do we still need to reduce the height of it?
3. I checked the code on dev and prod. The "CCTV Videos" panel will be shown only when selected is "Active Sewer Mains" or "Lateral Address Points". Do I need to add "Force Mains" and "Abandoned Sewer Mains"?

**Comment by JMurk** [comment]
1. Nope, the show hide function works.
2. Yes please.  The records never take up more than half of the space. So please decrease.
3. No, let's just leave it with those two for now.

A couple other things:
- Can the size of the window be dynamic to what is shown? Basically, remove all the blank space.
  ![image](https://cloud.githubusercontent.com/assets/5805454/13812667/e051587c-eb53-11e5-8da5-398d48a4f5ed.png)
- If nothing is available, can we just show a message in the pop-up that states "No Related Documents Available"
  ![image](https://cloud.githubusercontent.com/assets/5805454/13812752/4ba4a340-eb54-11e5-8726-0904b0dfbacc.png)

**Comment by taojun545** [comment]
Updated on dev.

**Comment by JMurk** [comment]
Confirmed complete on dev.  Please push to prod.

**Comment by taojun545** [comment]
Updated on prod.

**Comment by JMurk** [comment]
Confirmed complete.
