### ISSUE TITLE
Utility Viewer - Main Shutdown - Error

### ISSUE THREAD

**Issue by alanfoster99** [JMurk/Utility_Viewer_Issues#176]
When attempting shutdown trace on WDD25__0168885M or WDD25__0172356M, the analysis fails.  Please examine.
![image](https://cloud.githubusercontent.com/assets/7118831/8065012/936e52e6-0eac-11e5-8742-8c86249a621d.png)

**Comment by gerrykelly** [comment]
This was due to a previously identified problem of valve TAGs with more than 15-characters (due to trailing spaces) getting into the valve status tables from the nightly update from Wach's data.  I added a line in the route to trim the trailing spaces and the trace works.  Please test and close issue if verified.

**Comment by alanfoster99** [comment]
Confirmed and closing.  Thanks!
