### ISSUE TITLE
Utility Viewer -  Main Trace - System Cannot Find Valves to Stop Flow

### ISSUE THREAD

**Issue by JMurk** [JMurk/Utility_Viewer_Issues#23]
Issue:  The main trace function is unable to find valves to stop water flow when it appears that it should.

Steps to recreate:
1. Navigate to Water Main ID WEE27__0093866M
2. Click Main Trace
3. Select the main noted in step 1
4. Click Perform Trace

Resolution:  Please investigate and resolve accordingly.

**Comment by gjmkelly** [comment]
It’s difficult to say when you could legitimately get the “No valves that can stop water flow found in first attempt …” message, but this would very rarely happen.   If this was actually the case, the trace routine has an option to retry by a much longer, but almost-sure-to-work method (but I’m not sure what the dashboard trace does as a fallback when this is actually the case (Lu?)).   

In my testing for main WEE27__0093866M, I took the step of creating a development environment on Joe’s city computer and revising the .NET/ArcMap version of the trace routine to run against the city databases.  Of course things worked fine.  So, with it working on the desktop but not on the website, Lu was able to make a good guess that it was not actually failing to trace and what the real problem was.  Lu got things working for on the dashboard trace for this situation until I could followup and figure out the route cause (thanks Lu!).  

What it seems to be is that one of the valves to be closed has a bypass valve and the trace routine sends back an XML record for the bypass valve, just like any other valve even though it’s not a feature in GIS or its own record in the valve table.  The problem was it was not providing Lu’s form some data as expected.  I don’t know how we’ve never encountered this problem before; it should be somewhat common.  Now, with Lu’s fix, you would see:

So, it works, but the attributes are not the same as for “real” valve features.  The trace code handles this properly (i.e. if the bypass valve has a condition of INOPERABLE and position left of “OPEN”/” INCORRECTLY OPEN” the trace will not use it or the parent valve as a barrier to flow).  I think this fix is suffient, but it might make sense to make the bypass valve condition and position consistent with other valves for the forms and reports in the dashboard.
